color: null
description: null
fieldLayouts:
  389ae2df-c5df-433f-a27d-6f3222d0f6f8:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-14T12:11:31+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4e56572a-869e-4d40-8d39-ac4242834f08
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-14T12:42:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 728d790c-3fb5-4d20-97ae-8726a276188a # heroImage
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6820990-70f2-430a-afe9-1fdc3cf7ebdb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-14T12:42:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: da472e3c-2ae7-4552-a84c-4475b3d793f7 # shortDescription
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bb844a12-130c-4a3b-9ecd-aaad18d00769
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c6ffcfa0-288e-466d-a5d8-0a49bc0a3672
        userCondition: null
handle: home
hasTitleField: true
icon: null
name: Home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
