altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  9449b6d6-232f-48ec-8a5f-04369946bd35:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-02T20:27:37+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 80e76c50-a79d-44a1-98a4-95549afd4a70
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 822cb84d-f0ed-4dd7-b292-7ed96ff06015
        userCondition: null
fs: imagesFs
handle: images
name: Images
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
