columnSuffix: null
handle: difficulty
instructions: null
name: Difficulty
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - easy
        -
          - value
          - easy
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - medium
        -
          - value
          - medium
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - hard
        -
          - value
          - hard
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
