columnSuffix: null
handle: shortDescription
instructions: null
name: shortDescription
searchable: false
settings:
  byteLimit: null
  charLimit: 400
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
