defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 82430dba-f3d3-47a0-9fd9-1f1d6bd3d9bc # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  07305713-956b-4990-b908-5ce9a96e4e3c: # recipes
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
